language: node_js
node_js:
  - "4"
before_install:
  - npm install mocha -g
branches:
  only:
    - master
cache:
  directories:
    - node_modules
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: Nexters/VolleyTalk_Server
  bucket: volleytalk-server
  region: ap-northeast-2
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: volleytalk-server
  key: latest.zip
  bundle_type: zip
  application: VolleyTalk_Server
  deployment_group: volleyTalk
  region: ap-northeast-2
  on: *2
script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip